import json

with open("data/characters.json") as f:
    chars = json.load(f)

tiers = {
    "Mario": "A",
    "Luigi": "S",
    "Donkey Kong": "B",
    "Link": "C",
    "Samus": "A",
    "Dark Samus": "A",
    "Yoshi": "S",
    "Kirby": "C",
    "Fox": "S",
    "Pikachu": "A",
    "Ness": "B",
    "Captain Falcon": "A",
    "Jigglypuff": "C",
    "Peach": "S",
    "Daisy": "S",
    "Bowser": "C",
    "Ice Climbers": "B",
    "Sheik": "B",
    "Zelda": "D",
    "Dr. Mario": "D",
    "Pichu": "B",
    "Falco": "A",
    "Marth": "D",
    "Lucina": "B",
    "Young Link": "B",
    "Ganondorf": "E",
    "Mewtwo": "D",
    "Roy": "A",
    "Chrom": "C",
    "Mr. Game & Watch": "S",
    "Meta Knight": "B",
    "Pit": "B",
    "Dark Pit": "B",
    "Zero Suit Samus": "B",
    "Wario": "A",
    "Snake": "S",
    "Ike": "D",
    "Pokemon Trainer": "B",
    "Diddy Kong": "S",
    "Lucas": "C",
    "Sonic": "S",
    "King Dedede": "D",
    "Olimar": "A",
    "Lucario": "C",
    "R.O.B.": "S",
    "Toon Link": "B",
    "Wolf": "A",
    "Villager": "D",
    "Mega Man": "A",
    "Wii Fit Trainer": "C",
    "Rosalina & Luma": "B",
    "Little Mac": "E",
    "Greninja": "A",
    "Mii Brawler": "A",
    "Mii Swordfighter": "D",
    "Mii Gunner": "C",
    "Palutena": "A",
    "Pac-Man": "B",
    "Robin": "C",
    "Shulk": "A",
    "Bowser Jr.": "C",
    "Duck Hunt": "B",
    "Ryu": "A",
    "Ken": "B",
    "Cloud": "A",
    "Corrin": "A",
    "Bayonetta": "A",
    "Inkling": "B",
    "Ridley": "C",
    "Simon": "E",
    "Richter": "E",
    "King K. Rool": "D",
    "Isabelle": "C",
    "Incineroar": "C",
    "Piranha Plant": "C",
    "Joker": "S",
    "Hero": "A",
    "Banjo & Kazooie": "C",
    "Terry": "B",
    "Byleth": "B",
    "Min Min": "S",
    "Steve": "S",
    "Sephiroth": "B",
    "Pyra/Mythra": "S",
    "Kazuya": "S",
    "Sora": "A"
}

for name, style in tiers.items():
    if name in chars:
        chars[name]["tier"] = style

with open("data/characters.json", "w") as f:
    json.dump(chars, f, indent=2)

print("Done.")